
<form id="editForm" action="save" method="POST">
    <ul class="form-style-1">
        <li>
            <label><?php echo $translate->z_xlt('Namespace')?> <span class="required">*</span></label>
            <input id="namespace" type="text" value="<?php echo $this->escapeHtml($db->namespace)?>" name="db[namespace]" required class="field-divided" placeholder="<?php echo $translate->z_xlt('Namespace')?>" />

        </li>
        <li>
            <label><?php echo $translate->z_xlt('Username')?> <span class="required">*</span></label>
            <input type="text" value="<?php echo $this->escapeHtml($db->username)?>" name="db[username]" required class="field-divided" placeholder="<?php echo $translate->z_xlt('Username')?>" />

        </li>
        <li>
            <label><?php echo $translate->z_xlt('Database name')?></label>
            <input type="text" value="<?php echo $this->escapeHtml($db->dbname)?>" name="db[dbname]" required class="field-divided" placeholder="<?php echo $translate->z_xlt('Database name')?>" />
        </li>
        <li>
            <label><?php echo $translate->z_xlt('Password')?> <span class="required">*</span></label>
            <input type="password"  name="db[password]" class="field-divided" <?php echo ($db->password) ? '' : 'required' ?> placeholder="<?php echo ($db->password) ? '****' : $translate->z_xlt('Password') ?>" />
        </li>
        <li>
            <label><?php echo $translate->z_xlt('Host')?> <span class="required">*</span></label>
            <input type="text" value="<?php echo ($db->host) ? $this->escapeHtml($db->host) : 'localhost' ?>" name="db[host]" required class="field-divided" placeholder="<?php echo $translate->z_xlt('Host')?>" />
        </li>
        <li>
            <label><?php echo $translate->z_xlt('Port')?> <span class="required">*</span></label>
            <input type="text" value="<?php echo ($db->port) ? $this->escapeHtml($db->port) : '3306' ?>" name="db[port]" required class="field-divided" placeholder="<?php echo $translate->z_xlt('Port')?>" onkeypress="return onlynumber(event,this);" />
        </li>
        <li>
            <input type="button" name="back" value="<?php echo $translate->z_xlt('Back')?>" onclick=" window.location.href = window.history.back(1);" />
            <input type="submit" value="<?php echo $translate->z_xlt('Save')?>" />
        </li>
    </ul>
</form>

