<?php

$title = xl('Additional Tables Inheritance');
$this->headTitle($title);
?>


<div id="loading" class="row">
    <div class="col-md-offset-2 col-md-8 loading-box">
        <div class="row">
            <div class="col-md-12 text-center">
                <img src="<?=$basePatch?>/images/pouring/hourglass.svg"></div>
            <div class="col-md-12 text-center"><h3><?php echo $translate->z_xlt('Loading') . '...'?></h3> </div>
            <div class="loading-message text-center"></div>
        </div>
    </div>
</div>

<div class="wrapper">
    <div class="popupdarkbackground"></div>
    <div class="main-content">

        <div class="title">
            <?= ($this->escapeHtml($title) . ' - ' . $clinic_name)?>
        </div>
        <div id="lists">

            <div class="container text-center">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <h2><?php echo $translate->z_xlt('Tables that will be inherited') . ":"?></h2>
                        <ul class="list-group">
                            <?php foreach($tables as $table){ ?>
                                <li class="list-group-item"><?php echo $table['table_name'];?></li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>

            <button type="button" name="sync" id="sync" class="btn btn-default">סנכרן</button>
        </div>
    </div>
</div>

