<?php

$title = xl('List');
$this->headTitle($title);
?>

<div id="loading" class="row">
    <div class="col-md-offset-2 col-md-8 loading-box">
        <div class="row">
            <div class="col-md-12 text-center">
                <img src="<?=$basePatch?>/images/pouring/hourglass.svg"></div>
            <div class="col-md-12 text-center"><h3><?php echo $translate->z_xlt('Loading') . '...'?></h3> </div>
            <div class="loading-message text-center"></div>
        </div>
    </div>
</div>
<div class="main-content">
        <div class="title">
            <?= ($this->escapeHtml($title) . ' - ' . $clinic_name)?>
        </div>
        <div id="lists">

            <div class="content">
                <table id="list-table" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th><?php echo $translate->z_xlt('Name') ?></th>
                        <th><?php echo $translate->z_xlt('Sync') ?> <input name="select_all" value="1" id="sync-select-all" type="checkbox" /></th>
                        <th><?php echo $translate->z_xlt('Ability_to_edit_in_the_clinic') ?> <input name="select_all" value="1" id="edit-select-all" type="checkbox" /></th>

                    </tr>
                    </thead>

                </table>
            </div>
            <button type="button" name="sync" id="sync" class="btn btn-default">סנכרן</button>
        </div>
</div>


