<?php echo $header; ?>

<div id="export_container" style=" margin-top: 26px;">
<button id="createPdf"><?php echo xlt('Export Pdf'); ?></button>
<button id="createExcel"><?php echo xlt('Export Excel'); ?></button>
</div>

<?php echo $this->$helper($data); ?>

<script>
    let filterInitialInfo;

    function exportReport(type){
        $(".dataTable").DataTable().ajax.reload(function(){
            let filters = collectFilters();
            let title =  ('<h3>'+$("#title").find('h3').text()+'</h3>'+$("#report_info").text()) ;
            let columns = [];
            $.each(columnsFields,function(e){columns[$(this)[0]['name']]=$(this)[0]['title'] });
            window.open("<?php echo $data['route']; ?>/" + type + "?filters="+JSON.stringify(filters)+"&title="+title+"&columns="+JSON.stringify(columnsFields));
        });
    }

    $(document).ready(function(){

        $("#until_date").after("<p id='date-message' style='display: none'> <small style='color: red;'><?php echo xlt('Must be later than starting date'); ?></small> </p>");

        $('#from_date, #until_date').on('focus click change', function () {
            $('#date-message').hide();
        });

        filterInitialInfo=collectFilters();

        $("#createPdf").on("click",function(){
            exportReport('pdf');
        });

        $("#createExcel").on("click",function(){
            exportReport('excel');
        });

        $("#clear").on("click",function(){
            cleanFilters(filterInitialInfo);
        });

    });
</script>
