<?php

use GenericTools\Library\UiComponents\Header\ClinikalHeaders;
$headers = new ClinikalHeaders();
$menuBottons[] = array('id' => 'go_back', 'title' => 'cancel');
?>
<style>

    #alredy-exists{
        display: none;
    }
    #general-error{
        display: none;
    }

</style>
<div id="add-edit-template" class="container">

    <?php echo $headers->titleWithButtons("Add/edit template" , $menuBottons);  ?>
    <div class="row">
        <div class="col-md-6 text-center">
            <?php if($showSuccessMsg): ?>
                <div id="success-msg" class="alert alert-success" role="alert">
                    <?php echo xlt('The action completed successfully')?>
                </div>
            <?php endif; ?>
            <div id="alredy-exists" class="alert alert-danger" role="alert">
                <?php echo xlt('This template already exists')?>
            </div>
            <div id="general-error" class="alert alert-danger" role="alert">
                <?php echo xlt('Error ouccored')?>
            </div>
        </div>
    </div>
    <div class="row row_padded">
        <div class="col-xs-12 col-md-12">
            <h3><?php echo xlt('Add a new template') ?></h3>
        </div>
        <div class="col-xs-12 col-md-8">
            <textarea id="new-template" class="form-control"></textarea>
        </div>
        <div class="col-xs-12 col-md-4">
            <button class="btn btn-secondary btn-sm btn-save" id="save-new"><?php echo xlt('Save'); ?></button>
        </div>
    </div>
    <hr />
    <div class="row row_padded">
        <div class="col-xs-12 col-md-12">
            <h3><?php echo xlt('Edit template') ?></h3>
        </div>
        <div class="col-xs-12 col-md-8">
            <label for="templates" class="control-label"><?php echo xlt("Selelct template").":"; ?></label>
            <select class="selectpicker form-control" id="templates" data-show-subtext="true" data-live-search="true">
                <option data-tokens="" value=""><?php echo xlt("Choose"); ?></option>
                <?php foreach ($templates as $templateId => $template): ?>
                    <option data-tokens="" data-active="<?php echo attr($template['activity'])?>" value="<?php echo attr($templateId)?>"><?php echo xlt($template['title']); ?></option>
                <?php endforeach; ?>
            </select>
            <span id="templates_error" class="error-message" style="display: none"> <?php echo xlt("Value is required"); ?> </span>
        </div>
    </div>
    <div class="row  row_padded">
        <div class="col-xs-10 col-md-8">
            <textarea class="form-control" id="update-box" name="update_box" disabled></textarea>
        </div>
        <div class="col-xs-2 col-md-2">
            <div class="col-xs-2 col-md-5">
                <label for="active" class="control-label"><?php echo xlt("Active").":"; ?></label>
            </div>
            <div id="active" class="col-xs-2 col-md-7">
                <label class="radio-inline fix_inline_radio"><input  id="active-yes" disabled="true" type="radio" value="1" name="optradio"><?php echo xlt("Yes"); ?></label>
                <label   class="radio-inline fix_inline_radio"><input id="active-no"  disabled="true" type="radio" value="0"name="optradio" ><?php echo xlt("No"); ?></label>
            </div>

        </div>
        <div class="col-xs-12 col-md-2">
            <button class="btn btn-secondary btn-sm btn-edit" id="update-template" disabled ><?php echo xlt('update'); ?></button>
            <button class="btn btn-secondary btn-sm btn-cancel" id="delete-template" disabled ><?php echo xlt('Delete'); ?></button>
        </div>
    </div>
</div>
<div id="inactive-alert" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php echo xlt('System notification') ?></h5>
                <button type="button" class="close close-popup" data-dismiss="modal" aria-label="Close" >
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><?php echo xlt('Are you sure you want to mark this template as inactive') ?>?</p>
                <p><?php echo xlt('In the action all the form fields are assigned of this template will be marked as inactive also') ?>.</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="run-update" class="btn btn-primary"><?php echo xlt('Yes, update') ?></button>
                <button type="button" class="btn btn-secondary close-popup" data-dismiss="modal"><?php echo xlt('Cancel') ?></button>
            </div>
        </div>
    </div>
</div>
<div id="delete-alert" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php echo xlt('System notification') ?></h5>
                <button type="button" class="close close-popup" data-dismiss="modal" aria-label="Close" >
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><?php echo xlt('Are you sure you want to delete the template') ?>?</p>
                <p><?php echo xlt('In the action all the form fields are assigned to this template will be deleted also') ?>.</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="run-delete" class="btn btn-primary"><?php echo xlt('Yes, delete') ?></button>
                <button type="button" class="btn btn-secondary close-popup" data-dismiss="modal"><?php echo xlt('Cancel') ?></button>
            </div>
        </div>
    </div>
</div>
<script>

    $('#templates').select2({
        <?php require($GLOBALS['srcdir'] . '/js/xl/select2.js.php'); ?>
    });

    $('#templates').on('change', function () {
        $('#update-box').val($('#templates>option:selected').text());
        $('#update-box').prop('disabled', false);
        $('#update-template').prop('disabled', false);
        $('#delete-template').prop('disabled', false);
        if ($('#templates>option:selected').data('active') == 1) {
            $('#active-yes').prop('checked', true);
            $('#active-no').prop('checked', false);
        } else {
            $('#active-yes').prop('checked', false);
            $('#active-no').prop('checked', true);
        }
        $('#active-yes').prop('disabled', false);
        $('#active-no').prop('disabled', false);
    });


    function save()
    {
        hideErrors();
        var newTemplate = $('#new-template').val();
        if(newTemplate.length === 0) {
            return showError('new-template')
        }

        var url= '<?php echo $this->basePath()?>/templates-management';
        var action="save-new-template";
        var success_redirect=url+'/add-edit-template?success_msg=1';

        $.ajax({
            url: url+"/"+action,
            data: {
               template: newTemplate
            },
            error: function(data) {
                if (data.status = 409) {
                    $('#alredy-exists').show();
                } else {
                    $('#general-error').show();
                }
            },
            dataType: 'json',
            success: function(data) {

                console.log(data);
                top.restoreSession();
                window.location=success_redirect;

            },
            type: 'POST'
        });
    }

    function update(){
        hideErrors();
        var newTemplate = $('#update-box').val();
        if(newTemplate.length === 0) {
            return showError('update-box')
        }

        if($('#active input:radio:checked').val() == 0) {
            return  $('#inactive-alert').show();
        }
        updateTemplate();
    }

    function updateTemplate() {
        $('#inactive-alert').hide();
        var data = {
            id:$('#templates>option:selected').val(),
            text: $('#update-box').val(),
            activity: $('#active input:radio:checked').val(),
            old_text: $('#templates>option:selected').text(),
            old_activity: $('#templates>option:selected').data('active')
        }

        var url= '<?php echo $this->basePath()?>/templates-management';
        var action="update-template";
        var success_redirect=url+'/add-edit-template?success_msg=1';

        $.ajax({
            url: url+"/"+action,
            data: data,
            error: function(data) {
                if (data.status = 409) {
                    $('#alredy-exists').show();
                } else {
                    $('#general-error').show();
                }
            },
            dataType: 'json',
            success: function(data) {
                top.restoreSession();
                window.location=success_redirect;
            },
            type: 'POST'
        });
    }

    function deleteTemplate() {
        $('#inactive-alert').hide();
        var data = {
            id:$('#templates>option:selected').val(),
        }

        var url= '<?php echo $this->basePath()?>/templates-management';
        var action="delete-template";
        var success_redirect=url+'/add-edit-template?success_msg=1';

        $.ajax({
            url: url+"/"+action,
            data: data,
            error: function(data) {
                $('#general-error').show();
            },
            dataType: 'json',
            success: function(data) {
                top.restoreSession();
                window.location=success_redirect;
            },
            type: 'POST'
        });
    }


    function showError(id)
    {
        $('#' + id + '_error').css('display','block');
        $('#' + id).css('border', 'solid 1px red');
    }

    function showSelect2Error(id)
    {
        $('#' + id + '_error').css('display','block');
        $('#select2-' + id + '-container').parent().css('border', 'solid 1px red');
    }

    function hideErrors()
    {
        $('select').css('border', '1px solid #ced4da');
        $('.select2-selection').css('border', '1px solid #ced4da');
        $('[id$="_error"]').css('display','none');
        $('#alredy-exists').hide();
        $('#general-error').hide();
        $('#success-msg').hide();
    }

    function goBack(e) {
        e.preventDefault();
        var url=  '<?php echo $this->basePath()?>'+'/templates-management';
        top.restoreSession();
        window.location=url;
    }

    $('#save-new').click(save)
    $('#update-template').click(update)
    $('#delete-template').click(function (){
        $('#delete-alert').show()
    })
    $('#run-update').click(updateTemplate)
    $('#run-delete').click(deleteTemplate)

    $('.close-popup').on('click', function () {
        $('#inactive-alert').hide();
        $('#delete-alert').hide();
    })
    $("#go_back").on( "click",function(e) {goBack(e)});

    $("#tab_title").html(<?php echo js_escape($title) ?>);
</script>
