<?php
/*******
Required params -
$langDir - (rtl/ltr)
$langCode  - (he/en)
$clinicName
 ******/
?>

<header style="font-family: Arial" dir="<?php echo text($langDir); ?>"  lang="<?php echo text($langCode); ?>">
    <table width="100%" style="border-bottom: 1px solid #000000; vertical-align: bottom; font-family: Arial,serif; font-size: 9pt; color: black;">
        <tr>
            <td width="40%" align="right">
                <p  lang="<?php echo text($langCode); ?>" style="font-family: Arial,serif; font-size: 9pt;"><?php echo xl("STATE OF ISRAEL");?></p>
                <p  lang="<?php echo text($langCode); ?>" style="font-family: Arial,serif; font-size: 9pt;"><?php echo xl("MINISTRY OF HEALTH");?></p>
                <p  lang="<?php echo text($langCode); ?>" style="font-family: Arial,serif; font-size: 9pt;"  ><?php echo  xlt("Health Office")." ".text($clinicName) ?></p>
            </td>
            <td width="20%"  align="center">
                <?php if(is_file($GLOBALS['OE_SITE_DIR'] . '/images/logo_1.png')): ?>
                    <?php if (isset($type) && $type === 'html'): ?>
                        <img src="<?php echo $GLOBALS['OE_SITE_WEBROOT'] . '/images/logo_1.png' ?>" width="126px" height="65px"/>
                    <?php else: ?>
                        <img src="var:logoHeader" width="126px" height="65px"/>
                    <?php endif; ?>
                <?php endif; ?>

            </td>
            <td width="40%"  align="left">
                <p  lang="en" style="text-align: left; font-family: Arial,serif; font-size: 9pt; ">STATE OF ISRAEL</p>
                <p  lang="en" style="text-align: left; font-family: Arial,serif; font-size: 9pt;">MINISTRY OF HEALTH</p>
                <p  lang="en" style="text-align: left; font-family: Arial,serif; font-size: 9pt;"  ><?php echo text( ($clinicNameEnglish==null)? "Your Clinic Name Here":  $clinicNameEnglish." "."Health Office") ?></p>
            </td>
        </tr>
    </table>
</header>

<div style="margin-right:80%;">
    <?php if($showDate!=false):?>
        <td><span dir="ltr" style="font-weight: bold;"><?php echo $showDate ; ?></span></td>
    <?php endif;?>
</div>
