
.SumoSelect > .CaptionCont > label {
/* position: absolute; */
top: -10px;
right: 10px;
width: 30px;
float: left;
position: inherit;
}


.SumoSelect > .CaptionCont > span {
display: block;
padding-right: 6px;
padding-left: 15px;
}

.SumoSelect > .optWrapper > .options  li.opt label {
position: relative !important;
left: -30px !important;
}

.SumoSelect > .CaptionCont{
border-radius: 4px;
border: 1px solid #0064db!important;
padding: 2px 3px;
margin: 3px!important;
}


.SumoSelect > .optWrapper > .options li.opt label, .SumoSelect .select-all > label {
margin-right: 25px !important;
}
.SumoSelect .select-all{
margin-right: 6px !important;
height: 34px; !important;
}
.SumoSelect > .optWrapper > .options li.opt label {
position: relative;
top: 4px;
}
